var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":202,"id":273,"methods":[{"el":40,"sc":2,"sl":39},{"el":43,"sc":2,"sl":41},{"el":48,"sc":2,"sl":44},{"el":63,"sc":2,"sl":51},{"el":73,"sc":2,"sl":65},{"el":124,"sc":4,"sl":117},{"el":127,"sc":2,"sl":75},{"el":134,"sc":2,"sl":129},{"el":154,"sc":6,"sl":147},{"el":159,"sc":6,"sl":157},{"el":168,"sc":2,"sl":136},{"el":180,"sc":2,"sl":170},{"el":193,"sc":6,"sl":189},{"el":197,"sc":2,"sl":184},{"el":201,"sc":2,"sl":199}],"name":"ListTrackFragment","sl":29}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_11":{"methods":[{"sl":117}],"name":"test_step001_ObjectsExist","pass":true,"statements":[]},"test_15":{"methods":[{"sl":75},{"sl":129},{"sl":136},{"sl":147},{"sl":157},{"sl":170}],"name":"test_step002_Deleting","pass":true,"statements":[]},"test_40":{"methods":[{"sl":39}],"name":"test_step014_ForgetPasswordDialogSuccessLogin","pass":true,"statements":[]},"test_56":{"methods":[{"sl":44},{"sl":51},{"sl":65},{"sl":75}],"name":"test4_ND_ListTrack_Item","pass":true,"statements":[]},"test_8":{"methods":[{"sl":39}],"name":"test_step003_Discard","pass":true,"statements":[]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [40, 8], [], [], [], [], [56], [], [], [], [], [], [], [56], [], [], [], [], [], [], [], [], [], [], [], [], [], [56], [], [], [], [], [], [], [], [], [], [56, 15], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [11], [], [], [], [], [], [], [], [], [], [], [], [15], [], [], [], [], [], [], [15], [], [], [], [], [], [], [], [], [], [], [15], [], [], [], [], [], [], [], [], [], [15], [], [], [], [], [], [], [], [], [], [], [], [], [15], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
