var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":169,"id":42,"methods":[{"el":36,"sc":5,"sl":34},{"el":56,"sc":5,"sl":39},{"el":74,"sc":5,"sl":59},{"el":84,"sc":5,"sl":77},{"el":92,"sc":5,"sl":87},{"el":103,"sc":5,"sl":95},{"el":112,"sc":5,"sl":106},{"el":124,"sc":5,"sl":115},{"el":136,"sc":5,"sl":127},{"el":156,"sc":5,"sl":139},{"el":167,"sc":5,"sl":162}],"name":"Test006_BMIActivity","sl":20}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_0":{"methods":[{"sl":106}],"name":"test_step005_IdealWeight","pass":true,"statements":[]},"test_20":{"methods":[{"sl":95}],"name":"test_step004_WorkingWithSpinners","pass":true,"statements":[]},"test_3":{"methods":[{"sl":59}],"name":"test_step001_ObjectsExists","pass":true,"statements":[]},"test_31":{"methods":[{"sl":139},{"sl":162}],"name":"test_step008_FieldsWith0","pass":true,"statements":[]},"test_34":{"methods":[{"sl":77}],"name":"test_step002_ButtonsClickable","pass":true,"statements":[]},"test_35":{"methods":[{"sl":87}],"name":"test_step003_CalculateBMI","pass":true,"statements":[]},"test_44":{"methods":[{"sl":127},{"sl":162}],"name":"test_step007_EmptyFields","pass":true,"statements":[]},"test_55":{"methods":[{"sl":115}],"name":"test_step006_Clear","pass":true,"statements":[]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [3], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [34], [], [], [], [], [], [], [], [], [], [35], [], [], [], [], [], [], [], [20], [], [], [], [], [], [], [], [], [], [], [0], [], [], [], [], [], [], [], [], [55], [], [], [], [], [], [], [], [], [], [], [], [44], [], [], [], [], [], [], [], [], [], [], [], [31], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [44, 31], [], [], [], [], [], [], []]
