var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":183,"id":29,"methods":[{"el":27,"sc":5,"sl":25},{"el":33,"sc":5,"sl":30},{"el":48,"sc":5,"sl":36},{"el":66,"sc":5,"sl":51},{"el":79,"sc":5,"sl":69},{"el":96,"sc":5,"sl":82},{"el":110,"sc":5,"sl":99},{"el":124,"sc":5,"sl":113},{"el":139,"sc":5,"sl":127},{"el":153,"sc":5,"sl":142},{"el":160,"sc":5,"sl":156},{"el":171,"sc":5,"sl":166},{"el":181,"sc":5,"sl":177}],"name":"Test007_Navigation","sl":20}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_12":{"methods":[{"sl":69},{"sl":177}],"name":"test3_ND_Home_Item","pass":true,"statements":[]},"test_22":{"methods":[{"sl":51},{"sl":177}],"name":"test2_NavigationDrawerSlide","pass":true,"statements":[]},"test_29":{"methods":[{"sl":127},{"sl":177}],"name":"test7_ND_StopWatch_Item","pass":true,"statements":[]},"test_30":{"methods":[{"sl":113},{"sl":177}],"name":"test6_ND_Compass_Item","pass":true,"statements":[]},"test_32":{"methods":[{"sl":156},{"sl":166}],"name":"test9_HomeActivityBack","pass":true,"statements":[]},"test_45":{"methods":[{"sl":99},{"sl":177}],"name":"test5_ND_Graphs_Item","pass":true,"statements":[]},"test_54":{"methods":[{"sl":142},{"sl":177}],"name":"test8_ND_BMI_Item","pass":true,"statements":[]},"test_56":{"methods":[{"sl":82},{"sl":177}],"name":"test4_ND_ListTrack_Item","pass":true,"statements":[]},"test_6":{"methods":[{"sl":36},{"sl":177}],"name":"test1_NavigationDrawerActionBar","pass":true,"statements":[]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [6], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [22], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [12], [], [], [], [], [], [], [], [], [], [], [], [], [56], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [45], [], [], [], [], [], [], [], [], [], [], [], [], [], [30], [], [], [], [], [], [], [], [], [], [], [], [], [], [29], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [54], [], [], [], [], [], [], [], [], [], [], [], [], [], [32], [], [], [], [], [], [], [], [], [], [32], [], [], [], [], [], [], [], [], [], [], [56, 54, 45, 12, 22, 29, 6, 30], [], [], [], [], [], []]
