var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":167,"id":74,"methods":[{"el":47,"sc":5,"sl":45},{"el":62,"sc":5,"sl":49},{"el":70,"sc":5,"sl":65},{"el":76,"sc":5,"sl":73},{"el":82,"sc":5,"sl":79},{"el":88,"sc":5,"sl":85},{"el":94,"sc":5,"sl":91},{"el":100,"sc":5,"sl":97},{"el":114,"sc":5,"sl":102},{"el":124,"sc":5,"sl":116},{"el":141,"sc":5,"sl":126},{"el":152,"sc":5,"sl":145},{"el":165,"sc":5,"sl":158}],"name":"Test003_RegisterActivity","sl":31}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_1":{"methods":[{"sl":73}],"name":"test_step002_VerifyPasswordET","pass":true,"statements":[]},"test_10":{"methods":[{"sl":102}],"name":"test_step007_EmptyTwoFields","pass":true,"statements":[]},"test_13":{"methods":[{"sl":79}],"name":"test_step003_SecyrityHintET","pass":true,"statements":[]},"test_14":{"methods":[{"sl":116}],"name":"test_step008_FieldsFilledByUnusualSymbols","pass":true,"statements":[]},"test_18":{"methods":[{"sl":91}],"name":"test_step005_RegisterButtonExists","pass":true,"statements":[]},"test_21":{"methods":[{"sl":65}],"name":"test_step001_PasswordET","pass":true,"statements":[]},"test_25":{"methods":[{"sl":97}],"name":"test_step006_EmptyAllFields","pass":true,"statements":[]},"test_38":{"methods":[{"sl":85}],"name":"test_step004_ShowPasswordCB","pass":true,"statements":[]},"test_57":{"methods":[{"sl":126}],"name":"test_step009_PasswordsHidingByCheckBox","pass":true,"statements":[]},"test_7":{"methods":[{"sl":145}],"name":"test_step010_EnterValuesForFurtherTesting","pass":true,"statements":[]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [21], [], [], [], [], [], [], [], [1], [], [], [], [], [], [13], [], [], [], [], [], [38], [], [], [], [], [], [18], [], [], [], [], [], [25], [], [], [], [], [10], [], [], [], [], [], [], [], [], [], [], [], [], [], [14], [], [], [], [], [], [], [], [], [], [57], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [7], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
