var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":197,"id":57,"methods":[{"el":28,"sc":5,"sl":26},{"el":41,"sc":5,"sl":30},{"el":48,"sc":5,"sl":44},{"el":54,"sc":5,"sl":51},{"el":60,"sc":5,"sl":57},{"el":66,"sc":5,"sl":63},{"el":72,"sc":5,"sl":69},{"el":80,"sc":5,"sl":75},{"el":87,"sc":5,"sl":82},{"el":94,"sc":5,"sl":89},{"el":116,"sc":5,"sl":97},{"el":131,"sc":5,"sl":118},{"el":146,"sc":5,"sl":133},{"el":161,"sc":5,"sl":148},{"el":174,"sc":5,"sl":164},{"el":180,"sc":5,"sl":177},{"el":195,"sc":5,"sl":188}],"name":"Test004_LoginActivity","sl":15}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_19":{"methods":[{"sl":44}],"name":"test_step001_PasswordET","pass":true,"statements":[]},"test_24":{"methods":[{"sl":69}],"name":"test_step005_ActionBar","pass":true,"statements":[]},"test_26":{"methods":[{"sl":51}],"name":"test_step002_ButtonsExists","pass":true,"statements":[]},"test_40":{"methods":[{"sl":164}],"name":"test_step014_ForgetPasswordDialogSuccessLogin","pass":true,"statements":[]},"test_41":{"methods":[{"sl":57}],"name":"test_step003_ButtonsClickable","pass":true,"statements":[]},"test_43":{"methods":[{"sl":63}],"name":"test_step004_ForgetPasswordLabel","pass":true,"statements":[]},"test_9":{"methods":[{"sl":177}],"name":"test_step015_ForgetPasswordDialogAutoLogin","pass":true,"statements":[]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [19], [], [], [], [], [], [], [26], [], [], [], [], [], [41], [], [], [], [], [], [43], [], [], [], [], [], [24], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [40], [], [], [], [], [], [], [], [], [], [], [], [], [9], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]
